# -*- coding: utf-8 -*-
"""AI FEMHACK 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuPkPjY3q4BsiUu8Mtbwue1g1duUmnpa
"""

pip install opencv-python pytesseract pillow numpy

import cv2
import numpy as np
from PIL import Image
import pytesseract

def preprocess_image(image_path):
    img = cv2.imread(image_path)

    if img is None:
        return None

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Noise removal
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Thresholding
    _, thresh = cv2.threshold(blurred, 150, 255, cv2.THRESH_BINARY)

    return thresh

def extract_text(image):
    text = pytesseract.image_to_string(image)
    return text

import re
import pandas as pd

def parse_receipt(text):
    lines = text.split('\n')
    data = []

    # Updated regex to match item, optional quantity (like '2L' or '2'), and float price
    # Example matches: "Milk 2L $3.5", "Cheese $4.00", "White Bread $2.00"
    # Regex: (item_name) (optional_quantity) $(price)
    regex = r'^(.*?)(?:\s+(\d+L|\d+))?\s+\$(\d+\.?\d*)$'

    for line in lines:
        match = re.match(regex, line.strip()) # Use strip to remove leading/trailing whitespace
        if match:
            item = match.group(1).strip() # Item name, strip any extra spaces
            quantity_str = match.group(2) # Raw quantity string (e.g., '2L', '2', or None)
            price_str = match.group(3)    # Raw price string (e.g., '3.5', '4.00')

            # Process quantity
            if quantity_str:
                quantity = int(quantity_str.replace('L', ''))
            else:
                quantity = 1 # Default quantity if not specified

            # Process price
            price = float(price_str)

            data.append([item, quantity, price])

    df = pd.DataFrame(data, columns=['Item', 'Quantity', 'Price'])
    return df

category_map = {
    "Milk": "Dairy",
    "Cheese": "Dairy",
    "Bread": "Bakery",
    "Eggs": "Dairy",
    "Chicken": "Meat",
    "Chips": "Snacks"
}

def categorize_items(df):
    df['Category'] = df['Item'].map(category_map)
    return df

def analyze_spending(df):
    total_spent = df['Price'].sum()

    category_summary = df.groupby('Category')['Price'].sum().reset_index()
    category_summary['Percentage'] = (category_summary['Price'] / total_spent) * 100

    return total_spent, category_summary

!pip install google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyAmba8-XOIIBZMqUWj4GCvTgmtQ5miBdzs")

model = genai.GenerativeModel("gemini-flash-latest")

response = model.generate_content("Hello, give me 3 budgeting tips.")
print(response.text)



for m in genai.list_models():
  if "generateContent" in m.supported_generation_methods:
    print(m.name)

def generate_llm_advice(summary_df):
    prompt = "Given the following spending summary, provide personalized budgeting advice. Focus on areas where spending is high or could be optimized:\n\n"
    prompt += summary_df.to_string(index=False)
    prompt += "\n\nBased on this, what are 3 key budgeting tips for this user?"

    response = model.generate_content(prompt)
    return response.text

from google.colab import files
uploaded = files.upload()  # Ye ek upload button dikhayega

# Assuming you have a receipt image named 'Screenshot 2026-02-15 112620.png' uploaded
image_path = 'Screenshot 2026-02-15 112620.png'

# 1. Preprocess the image
preprocessed_img = preprocess_image(image_path)

if preprocessed_img is None:
    print(f"Error: Image at '{image_path}' could not be loaded. Please upload the file and try again.")
else:
    # 2. Extract text
    extracted_text = extract_text(preprocessed_img)

    # 3. Parse the receipt
    receipt_df = parse_receipt(extracted_text)

    # 4. Categorize items
    categorized_df = categorize_items(receipt_df)

    # 5. Analyze spending
    total_spent, summary_df = analyze_spending(categorized_df)

    print("Total Spent:", total_spent)
    print("Category Summary:")
    print(summary_df)

import re
import pandas as pd

# Use the already extracted text from the receipt image
text = extracted_text
lines = text.split("\n")
data = []

for line in lines:
    # Updated regex to correctly capture item (group 1) and price (group 2)
    match = re.search(r'([A-Za-z ]+)[ ]+\$((?:\d+\.)?\d+)', line)
    if match:
        item = match.group(1).strip()
        price = float(match.group(2))
        data.append([item, price])

df = pd.DataFrame(data, columns=["Item", "Price"])
print(df)

def generate_llm_advice(summary_df):
    prompt = "Given the following spending summary, provide personalized budgeting advice. Focus on areas where spending is high or could be optimized:\n\n"
    prompt += summary_df.to_string(index=False)
    prompt += "\n\nBased on this, what are 3 key budgeting tips for this user?"

    response = model.generate_content(prompt)
    return response.text

advice = generate_llm_advice(summary_df)
print("AI Advice:\n", advice)

import matplotlib.pyplot as plt

plt.bar(summary_df["Category"], summary_df["Percentage"], color=["blue","red","green"])
plt.title("Spending Distribution")
plt.ylabel("Percentage of Total")
plt.show()

print("=== Spending Summary ===")
print(summary_df)
print("\n=== Total Spent ===")
print(total_spent)
print("\n=== AI-Generated Advice ===")
print(advice)

summary_df['Overspending'] = summary_df['Percentage'] > 40  # True for high %
print(summary_df)

